### ISSUE TITLE
import directives reference JS files where in fact no such file exists in type=TS

### ISSUE THREAD

**Issue by jeffsaremi** [wasilibs/go-protoc-gen-es#40]
Version:
go install github.com/wasilibs/go-protoc-gen-es/cmd/protoc-gen-es@v1.10.0

This is how I'm using the `go-protoc-gen-es` to generate TypeScript files for my proto definitions

```
  - name: es
    out: ./web/src/gen/ts
    opt:
      - target=ts
```
I can see the generated files with no issue
Vscode shows no problems with the imports however imports like these runtime problems:

```
import { Account, Project, Team } from "./common_pb.js";
```

Error from runtime:
```
ERROR in ./src/gen/ts/service/v2/migrations_pb.ts 9:0-56
Module not found: Error: Can't resolve './common_pb.js' in '.../web/src/gen/ts/service/v2'
```

If I manually change the import line to : `import { Account, Project, Team } from "./common_pb";` then the problem goes away. However the next time I generate code it gets overwritten again

**Comment by jeffsaremi** [comment]
Closing this it is already solved in protoc-gen-es!

**Comment by anuraaga** [comment]
Hi @jeffsaremi - you probably already found it but just in case or for anyone else that stumbles on this issue, for v1 you can add `import_extension=none` option for that behavior, while in v2 it is the default behavior.
